name: Github Pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      if: github.event.deleted == false
      with:
        python-version: '3.8'
        architecture: 'x64'
    - name: Install dependencies
      if: success()
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry export -f requirements.txt -o requirements.txt --dev
        pip install -r requirements.txt
    - name: Build with MkDocs
      if: success()
      run: pydocmd build
    - name: Deploy to GitHub Pages
      uses: docker://peaceiris/gh-pages:latest
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_build/site
